CREATE SCHEMA CLINICA;

CREATE TABLE CLINICA.MEDICO (
			ID_MEDICO INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
			NOME TEXT NOT NULL,
			CRM  TEXT NOT NULL,
			ESPECIALIDADE TEXT NOT NULL
);


CREATE TABLE CLINICA.PACIENTE (
			ID_PACIENTE INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
			CPF VARCHAR(11) NOT NULL,
			NOME TEXT NOT NULL,
			IDADE INT NOT NULL,
			DATA_NASC TIMESTAMP NOT NULL
);


CREATE TABLE CLINICA.CONSULTA(
			ID_CONSULTA INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
			DATA TIMESTAMP NOT NULL,
			ID_MEDICO INT NOT NULL,
			ID_CLINICA INT NOT NULL,
			ID_PACIENTE INT NOT NULL,
			
			-- MANEIRA EXTENSA
			FOREIGN KEY (ID_MEDICO)
			REFERENCES CLINICA.MEDICO(ID_MEDICO),
			FOREIGN KEY (ID_CLINICA)
			REFERENCES CLINICA.CLINICA(ID_CLINICA),
			FOREIGN KEY (ID_PACIENTE)
			REFERENCES CLINICA.PACIENTE(ID_PACIENTE)
			
			-- MANEIRA ABREVIDA
--			ID_MEDICO INT NOT NULL REFERENCES CLINICA.MEDICO(ID_MEDICO),
--			ID_CLINICA INT NOT NULL REFERENCES CLINICA.CLINICA(ID_CLINICA),
--			ID_PACIENTE INT NOT NULL REFERENCES CLINICA.PACIENTE(ID_PACIENTE)

);
	

CREATE TABLE CLINICA.CLINICA (
			ID_CLINICA INT PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
			NOME TEXT NOT NULL,
			DESCICAO TEXT NOT NULL,
			ENDERECO TEXT NOT NULL
);

drop table clinca.consulta 


